### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by setarekhosravi** [ltShi/EVPTrack#1]
Hi! Thank you for your great work. 
I want to run `video_demo.py`, everything is okay when I use the command below I see an error.
command: 
`python ./tracking/video_demo.py evptrack EVPTrack-full-224 [path to video] --optional_box 584 382 81 32`
The error:
`test config:  {'MODEL': {'PRETRAIN_FILE': 'mae_hivit_base_1600ep.pth', 'EXTRA_MERGER': False, 'RETURN_INTER': False, 'RETURN_STAGES': [2, 5, 8, 11], 'BACKBONE': {'TYPE': 'hivit_base', 'STRIDE': 16, 'MID_PE': False, 'SEP_SEG': False, 'CAT_MODE': 'direct', 'MERGE_LAYER': 0, 'ADD_CLS_TOKEN': False, 'CLS_TOKEN_USE_MODE': 'ignore', 'CE_LOC': [], 'CE_KEEP_RATIO': [], 'CE_TEMPLATE_RANGE': 'ALL'}, 'HEAD': {'TYPE': 'CENTER', 'NUM_CHANNELS': 256}}, 'TRAIN': {'LR': 0.0004, 'WEIGHT_DECAY': 0.0001, 'EPOCH': 150, 'LR_DROP_EPOCH': 120, 'BATCH_SIZE': 4, 'NUM_WORKER': 5, 'OPTIMIZER': 'ADAMW', 'BACKBONE_MULTIPLIER': 0.1, 'GIOU_WEIGHT': 2.0, 'L1_WEIGHT': 5.0, 'FREEZE_LAYERS': [0], 'PRINT_INTERVAL': 50, 'VAL_EPOCH_INTERVAL': 100, 'GRAD_CLIP_NORM': 0.1, 'AMP': False, 'CE_START_EPOCH': 20, 'CE_WARM_EPOCH': 80, 'DROP_PATH_RATE': 0.1, 'SCHEDULER': {'TYPE': 'step', 'DECAY_RATE': 0.1}}, 'DATA': {'SAMPLER_MODE': 'causal', 'MEAN': [0.485, 0.456, 0.406], 'STD': [0.229, 0.224, 0.225], 'MAX_SAMPLE_INTERVAL': 200, 'TRAIN': {'DATASETS_NAME': ['LASOT', 'GOT10K_vottrain', 'COCO17', 'TRACKINGNET'], 'DATASETS_RATIO': [1, 1, 1, 1], 'SAMPLE_PER_EPOCH': 7500}, 'VAL': {'DATASETS_NAME': ['GOT10K_votval'], 'DATASETS_RATIO': [1], 'SAMPLE_PER_EPOCH': 1250}, 'SEARCH': {'SIZE': 224, 'FACTOR': 4.0, 'CENTER_JITTER': 3.5, 'SCALE_JITTER': 0.5, 'NUMBER': 8}, 'TEMPLATE': {'NUMBER': 1, 'SIZE': 112, 'FACTOR': 2.0, 'CENTER_JITTER': 0, 'SCALE_JITTER': 0}}, 'TEST': {'TEMPLATE_FACTOR': 2.0, 'TEMPLATE_SIZE': 112, 'SEARCH_FACTOR': 4.0, 'SEARCH_SIZE': 224, 'EPOCH': 145}}
Traceback (most recent call last):
  File "/media/strh/MyDrive/Track/OtherTracking/EVPTrack/tracking/video_demo.py", line 39, in <module>
    main()
  File "/media/strh/MyDrive/Track/OtherTracking/EVPTrack/tracking/video_demo.py", line 35, in main
    run_video(args.tracker_name, args.tracker_param, args.videofile, args.optional_box, args.debug, args.save_results)
  File "/media/strh/MyDrive/Track/OtherTracking/EVPTrack/tracking/video_demo.py", line 20, in run_video
    tracker.run_video(videofilepath=videofile, optional_box=optional_box, debug=debug, save_results=save_results)
  File "/media/strh/MyDrive/Track/OtherTracking/EVPTrack/lib/test/evaluation/tracker.py", line 176, in run_video
    tracker = self.create_tracker(params)
  File "/media/strh/MyDrive/Track/OtherTracking/EVPTrack/lib/test/evaluation/tracker.py", line 65, in create_tracker
    tracker = self.tracker_class(params, self.dataset_name)
  File "/media/strh/MyDrive/Track/OtherTracking/EVPTrack/lib/test/tracker/evptrack.py", line 23, in __init__
    network.load_state_dict(torch.load(self.params.checkpoint, map_location='cpu')['net'], strict=True)
  File "/home/strh/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for EVPTrack:
	Missing key(s) in state_dict: "backbone.STE_norm.weight", "backbone.STE_norm.bias", "backbone.STE.norm1.weight", "backbone.STE.norm1.bias", "backbone.STE.attn.qkv.weight", "backbone.STE.attn.qkv.bias", "backbone.STE.attn.proj.weight", "backbone.STE.attn.proj.bias", "backbone.STE.norm2.weight", "backbone.STE.norm2.bias", "backbone.STE.mlp.fc1.weight", "backbone.STE.mlp.fc1.bias", "backbone.STE.mlp.fc2.weight", "backbone.STE.mlp.fc2.bias", "backbone.MSPG.weight", "backbone.STPG.weight". 
	Unexpected key(s) in state_dict: "backbone.history_norm.weight", "backbone.history_norm.bias", "backbone.history_module.norm1.weight", "backbone.history_module.norm1.bias", "backbone.history_module.attn.qkv.weight", "backbone.history_module.attn.qkv.bias", "backbone.history_module.attn.proj.weight", "backbone.history_module.attn.proj.bias", "backbone.history_module.norm2.weight", "backbone.history_module.norm2.bias", "backbone.history_module.mlp.fc1.weight", "backbone.history_module.mlp.fc1.bias", "backbone.history_module.mlp.fc2.weight", "backbone.history_module.mlp.fc2.bias", "backbone.adaptor_s.weight", "backbone.adaptor_h.weight". `

Please help me to solve this problem.

**Comment by ltShi** [comment]
I've updated the model weights and you can re-download the new version.

**Comment by setarekhosravi** [comment]
@ltShi Thank you for your response!
